stages:
  harmonize_eo_data:
    cmd: python src/data/harmonize_eo_data.py -n 12 # 12 is max procs w/ 250 GB RAM
    deps:
      - src/data/harmonize_eo_data.py
    params:
      - model_res
      - mask
      - datasets.X
      - base_resolution
      - target_resolution
      - eo_data.interim.dir
      - worldclim.bio_vars
    outs:
      - ${eo_data.interim.dir}/${model_res}:
          persist: false

  get_TRY_mean_traits:
    cmd: python src/data/build_try_traits.py
    deps:
      - src/data/build_try_traits.py
      - ${trydb.raw.dir}/${trydb.raw.zip}
    params:
      - trydb.raw.dir
      - trydb.raw.zip
      - trydb.raw.zipfile_csv
      - trydb.interim
    outs:
      - ${trydb.interim.dir}/${trydb.interim.filtered}

  match_gbif_pfts:
    cmd: python src/data/match_gbif_pfts.py
    deps:
      - src/data/match_gbif_pfts.py
      - ${gbif.raw.dir}
      - ${trydb.raw.pfts}
    params:
      - datasets.Y.gbif
      - gbif.raw.dir
      - gbif.interim.dir
      - gbif.interim.matched
    outs:
      - ${gbif.interim.dir}/${gbif.interim.matched}:
          persist: true

  subsample_gbif:
    cmd: python src/data/subsample_gbif.py
    deps:
      - src/data/subsample_gbif.py
      - ${gbif.interim.dir}/${gbif.interim.matched}
    params:
      - gbif.interim.dir
      - gbif.interim.matched
      - gbif.interim.subsampled
      - gbif.interim.subsample_binsize
      - gbif.interim.subsample_n_max
      - random_seed
    outs:
      - ${gbif.interim.dir}/${gbif.interim.subsampled}:
          persist: true

  build_gbif_maps:
    cmd: python src/data/build_gbif_maps.py
    deps:
      - src/data/build_gbif_maps.py
      - ${gbif.interim.dir}/${gbif.interim.subsampled}
      - ${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - gbif.interim.dir
      - gbif.interim.subsampled
      - trydb.interim.dir
      - trydb.interim.filtered
      - datasets.Y.gbif
      - PFT
      - model_res
      - target_resolution
    outs:
      - ${gbif.interim.dir}/${gbif.interim.traits}/${PFT}/${model_res}:
          persist: true

  extract_splot:
    cmd: python src/data/extract_splot.py
    deps:
      - src/data/extract_splot.py
      - data/raw/${datasets.Y.splot}
    params:
      - datasets.Y.splot
      - splot.interim.dir
    outs:
      - ${splot.interim.dir}/${splot.interim.extracted}:
          persist: true

  build_splot_maps:
    cmd: python src/data/build_splot_maps.py
    deps:
      - src/data/build_splot_maps.py
      - ${splot.interim.dir}/${splot.interim.extracted}
      - ${trydb.raw.pfts}
      - ${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - splot.interim
      - model_res
      - PFT
      - target_resolution
    outs:
      - ${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}:
          persist: true

  # match_splot_pfts:
  #   cmd: python src/data/match_splot_pfts.py
  #   deps:
  #     - src/data/match_splot_pfts.py
  #     - ${splot.interim.dir}
  #     - ${trydb.raw.pfts}
  #   params:
  #     - datasets.Y.splot
  #     - splot.interim
  #   outs:
  #     - ${splot.interim.dir}/${splot.interim.matched}:
  #         persist: true
  # harmonize_trait_data:
  #   cmd: python src/data/harmonize_trait_data.py
  #   deps:
  #     - src/data/harmonize_trait_data.py
  #     - data/raw/${datasets.Y.splot}
  #     - data/raw/${datasets.Y.gbif}
  #   params:
  #     - model_res
  #     - mask
  #     - datasets.Y
  #     - base_resolution
  #     - target_resolution
  #     - extent
  #     - interim.traits
  #   outs:
  #     - ${interim.traits}/${model_res}:
  #         persist: true

  # calculate_ndvi:
  #   cmd: python src/data/calculate_ndvi.py
  #   deps:
  #     - src/data/calculate_ndvi.py
  #     - ${eo_data.interim.dir}/${model_res}
  #   outs:
  #     - ${eo_data.interim.dir}/${model_res}:
  #         persist: true

  # prune_bio_vars:
  #   cmd: python src/data/prune_bio_vars.py
  #   deps:
  #     - src/data/prune_bio_vars.py
  #     - ${eo_data.interim.dir}/${model_res}
  #   outs:
  #     - ${eo_data.interim.dir}/${model_res}:
  #         persist: true

  # build_train:
  #   cmd: python src/data/build_train.py
  #   deps:
  #     - src/data/build_train.py
  #     - ${eo_data.interim.dir}/${model_res}
  #   outs:
  #     - ${train.path}/${model_res}:
  #         persist: true

  # calculate_spatial_lag:
  #   cmd: python src/features/calculate_spatial_lag.py
  #   deps:
  #     - src/features/calculate_spatial_lag.py
  #     - ${train.path}/${model_res}
  #   outs:
  #     - ${train.path}/${model_res}/:
  #         persist: true
