stages:
  harmonize_eo_data:
    cmd: python src/data/harmonize_eo_data.py -n 12 # 12 is max procs w/ 250 GB RAM
    deps:
      - src/data/harmonize_eo_data.py
    params:
      - model_res
      - mask
      - datasets.X
      - base_resolution
      - target_resolution
      - eo_data.interim.dir
      - worldclim.bio_vars
    outs:
      - ${eo_data.interim.dir}/${model_res}:
          persist: false

  get_TRY_mean_traits:
    cmd: python src/data/build_try_traits.py
    deps:
      - src/data/build_try_traits.py
      - ${trydb.raw.dir}/${trydb.raw.zip}
    params:
      - trydb.raw.dir
      - trydb.raw.zip
      - trydb.raw.zipfile_csv
      - trydb.interim
    outs:
      - ${trydb.interim.dir}/${trydb.interim.filtered}

  match_gbif_pfts:
    cmd: python src/data/match_gbif_pfts.py
    deps:
      - src/data/match_gbif_pfts.py
      - ${gbif.raw.dir}
      - ${trydb.raw.pfts}
    params:
      - datasets.Y.gbif
      - gbif.raw.dir
      - gbif.interim.dir
      - gbif.interim.matched
    outs:
      - ${gbif.interim.dir}/${gbif.interim.matched}:
          persist: true

  subsample_gbif:
    cmd: python src/data/subsample_gbif.py
    deps:
      - src/data/subsample_gbif.py
      - ${gbif.interim.dir}/${gbif.interim.matched}
    params:
      - gbif.interim.dir
      - gbif.interim.matched
      - gbif.interim.subsampled
      - gbif.interim.subsample_binsize
      - gbif.interim.subsample_n_max
      - random_seed
    outs:
      - ${gbif.interim.dir}/${gbif.interim.subsampled}:
          persist: true

  build_gbif_maps:
    cmd: python src/data/build_gbif_maps.py
    deps:
      - src/data/build_gbif_maps.py
      - ${gbif.interim.dir}/${gbif.interim.subsampled}
      - ${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - gbif.interim.dir
      - gbif.interim.subsampled
      - trydb.interim.dir
      - trydb.interim.filtered
      - datasets.Y.gbif
      - PFT
      - model_res
      - target_resolution
    outs:
      - ${gbif.interim.dir}/${gbif.interim.traits}/${PFT}/${model_res}:
          persist: true

  extract_splot:
    cmd: python src/data/extract_splot.py
    deps:
      - src/data/extract_splot.py
      - data/raw/${datasets.Y.splot}
    params:
      - datasets.Y.splot
      - splot.interim.dir
    outs:
      - ${splot.interim.dir}/${splot.interim.extracted}:
          persist: true

  build_splot_maps:
    cmd: python src/data/build_splot_maps.py
    deps:
      - src/data/build_splot_maps.py
      - ${splot.interim.dir}/${splot.interim.extracted}
      - ${trydb.raw.pfts}
      - ${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - splot.interim
      - model_res
      - PFT
      - target_resolution
    outs:
      - ${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}:
          persist: true

  build_features:
    cmd: python src/features/featurize_train.py --nchunks 13
    deps:
      - src/features/featurize_train.py
      - ${eo_data.interim.dir}/${model_res}
      - ${gbif.interim.dir}/${gbif.interim.traits}/${PFT}/${model_res}
      - ${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}
    params:
      - PFT
      - model_res
      - eo_data.interim.dir
      - datasets.Y.trait_stat
      - datasets.Y.use
      - gbif.interim.dir
      - gbif.interim.traits
      - splot.interim.dir
      - splot.interim.traits
      - train.dir
      - train.features
    outs:
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.features}:
          persist: true

  calculate_spatial_autocorr:
    cmd: python src/features/calc_spatial_autocorr.py
    deps:
      - src/features/calc_spatial_autocorr.py
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.features}
    params:
      - train.spatial_autocorr
    outs:
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.spatial_autocorr}:
          persist: true

  build_cv_splits:
    cmd: python src/features/skcv_splits.py
    deps:
      - src/features/skcv_splits.py
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.features}
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.spatial_autocorr}
    params:
      - train.cv_splits
    outs:
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.cv_splits.dir}:
          persist: true

  train_models:
    cmd: python src/models/train_models.py
    deps:
      - src/models/train_models.py
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.features}
      - ${train.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.cv_splits.dir}
    params:
      - train.arch
      - ${train.arch}
    outs:
      - ${models.dir}/${PFT}/${model_res}/${datasets.Y.use}/${train.arch}:
          persist: true
