stages:
  ######################################################################################
  # RES-IND., PFT-DEP. STAGES ----------------------------------------------------------
  ######################################################################################

  get_TRY_mean_traits:
    cmd: python src/data/build_try_traits.py
    deps:
      - src/data/build_try_traits.py
      - ${raw_dir}/${trydb.raw.dir}/${trydb.raw.zip}
    params:
      - trydb
    outs:
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.filtered}:
          persist: false
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}:
          persist: false

  match_gbif_pfts:
    cmd: python src/data/match_gbif_pfts.py
    deps:
      - src/data/match_gbif_pfts.py
      - ${raw_dir}/${gbif.raw.dir}
      - ${raw_dir}/${trydb.raw.pfts}
    params:
      - datasets.Y.gbif
      - gbif.raw.dir
      - gbif.interim.dir
      - gbif.interim.matched
    outs:
      - ${interim_dir}/${gbif.interim.dir}/${gbif.interim.matched}:
          persist: false

  extract_splot:
    cmd: python src/data/extract_splot.py
    deps:
      - src/data/extract_splot.py
      - ${raw_dir}/${datasets.Y.splot}
    params:
      - datasets.Y.splot
      - splot.interim.dir
    outs:
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.extracted}:
          persist: false

  standardize_other_products:
    cmd: python src/data/standardize_other_products.py
    deps:
      - src/data/standardize_other_products.py
      - ${raw_dir}/other-trait-maps
    outs:
      - ${interim_dir}/other_trait_maps:
          persist: false

  ######################################################################################
  # RES-DEP., PFT-IND. -----------------------------------------------------------------
  ######################################################################################

  harmonize_eo_data:
    cmd: python src/data/harmonize_eo_data.py
    deps:
      - src/data/harmonize_eo_data.py
    params:
      - model_res
      - mask
      - datasets.X
      - base_resolution
      - target_resolution
      - eo_data.interim.dir
      - worldclim.bio_vars
    outs:
      - ${interim_dir}/${eo_data.interim.dir}/${model_res}:
          persist: false

  build_predict:
    cmd: python src/features/featurize_predict.py
    deps:
      - src/features/featurize_predict.py
      - ${interim_dir}/${eo_data.interim.dir}/${model_res}
    params:
      - model_res
      - train.dir
      - eo_data.interim.dir
      - eo_data.predict.dir
      - eo_data.predict.mask_fn
      - eo_data.predict.imputed_fn
    outs:
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}:
          persist: false
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}:
          persist: false


  ######################################################################################
  # RES DEP., PFT-DEP. STAGES ----------------------------------------------------------
  ######################################################################################
  
  build_gbif_maps:
    cmd: python src/data/build_gbif_maps.py
    deps:
      - src/data/build_gbif_maps.py
      - ${interim_dir}/${gbif.interim.dir}/${gbif.interim.matched}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - gbif.interim.dir
      - trydb.interim.dir
      - trydb.interim.filtered
      - datasets.Y.gbif
      - PFT
      - model_res
      - target_resolution
    outs:
      - ${interim_dir}/${gbif.interim.dir}/${gbif.interim.traits}/${PFT}/${model_res}:
          persist: false

  build_splot_maps:
    cmd: python src/data/build_splot_maps.py
    deps:
      - src/data/build_splot_maps.py
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.extracted}
      - ${raw_dir}/${trydb.raw.pfts}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.filtered}
    params:
      - splot.interim
      - model_res
      - PFT
      - target_resolution
    outs:
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}:
          persist: false

  build_y:
    cmd: python src/features/build_y.py
    deps:
      - src/features/build_y.py
      - ${interim_dir}/${gbif.interim.dir}/${gbif.interim.traits}/${PFT}/${model_res}
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}
    params:
      - datasets.Y.trait_stat
      - datasets.Y.traits

    outs:
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}

  calculate_spatial_autocorr:
    cmd: python src/features/calc_spatial_autocorr.py
    deps:
      - src/features/calc_spatial_autocorr.py
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
    params:
      - train.spatial_autocorr
      - calc_spatial_autocorr
    outs:
      - ${train.dir}/${PFT}/${model_res}/${train.spatial_autocorr}

  build_cv_splits:
    cmd: python src/features/skcv_splits.py -o
    deps:
      - src/features/skcv_splits.py
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
      - ${train.dir}/${PFT}/${model_res}/${train.spatial_autocorr}
    params:
      - train.cv_splits
    outs:
      - ${train.dir}/${PFT}/${model_res}/${train.cv_splits.dir}:
          persist: false

  train_models:
    cmd: python src/models/train_models.py -r && python src/models/cv_stats.py
    deps:
      - src/models/train_models.py
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
      - ${train.dir}/${PFT}/${model_res}/${train.cv_splits.dir}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}
    params:
      - train.arch
      - autogluon
      - datasets.Y.traits
    outs:
      - ${models.dir}/${PFT}/${model_res}:
          persist: false
  
  aoa:
    cmd: python src/analysis/aoa.py
    deps:
      - src/analysis/aoa.py
      - ${train.dir}/${PFT}/${model_res}/${train.Y.fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${models.dir}/${PFT}/${model_res}  # Feature importance
    params:
      - datasets.Y.traits
      - aoa
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${aoa.dir}:
          persist: false

  predict:
    cmd: python src/models/predict_traits.py -r -v
    deps:
      - src/models/predict_traits.py
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}
      - ${models.dir}/${PFT}/${model_res}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}
    params:
      - predict
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${predict.dir}:
          persist: false

  cov:
    cmd: python src/models/predict_traits.py -r -v --cov
    deps:
      - src/models/predict_traits.py
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.imputed_fn}
      - ${train.dir}/${eo_data.predict.dir}/${model_res}/${eo_data.predict.mask_fn}
      - ${models.dir}/${PFT}/${model_res}
      - ${interim_dir}/${trydb.interim.dir}/${trydb.interim.transformer_fn}
    params:
      - predict
      - cov
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${cov.dir}:
          persist: false

  build_final_product:
    cmd: python src/data/build_final_product.py -o
    deps:
      - src/data/build_final_product.py
      - reference/trait_mapping.json
      - reference/trait_stat_mapping.json
      - ${processed.dir}/${PFT}/${model_res}/${predict.dir}
      - ${processed.dir}/${PFT}/${model_res}/${cov.dir}
      - ${processed.dir}/${PFT}/${model_res}/${aoa.dir}
    params:
      - public
    outs:
      - ${processed.dir}/${PFT}/${model_res}/${public.local_dir}:
          persist: false

  aggregate_all_stats:
    cmd: python src/models/multires_stats.py -mfc
    deps:
      - src/models/multires_stats.py
      - ${models.dir}/${PFT}/${model_res}
    params:
      - analysis
  
  aggregate_aoa:
    cmd: python src/analysis/multires_aoa.py
    deps:
      - src/analysis/multires_aoa.py
      - ${processed.dir}/${PFT}/${model_res}/${aoa.dir}
  
  other_product_splot_correlation:
    cmd: python src/analysis/other_product_splot_correlation.py
    deps:
      - src/analysis/other_product_splot_correlation.py
      - ${interim_dir}/other_trait_maps
      - ${interim_dir}/${splot.interim.dir}/${splot.interim.traits}/${PFT}/${model_res}