model_res: "001"
PFT: "Shrub_Tree_Grass"
random_seed: 42
base_resolution: 0.01 # Shared best resolution of all EO datasets (used for masking)
target_resolution: 0.01 # Target resolution for model training
extent: [-180, -60, 180, 90] # Extent of the final dataset
raw_dir: data/raw
interim_dir: data/interim
processed_dir: data/processed
dask_dashboard: ":39143"

mask:
  path: data/raw/esa_worldcover_v100_1km/esa_worldcover_v100_1km.tif
  keep_classes:
    - 10 # Tree cover
    - 20 # Shrubland
    - 30 # Grassland
    - 40 # Cropland
    - 60 # Bare/sparse vegetation
    - 70 # Snow and ice
    - 90 # Herbaceous wetland
    - 95 # Mangroves
    - 100 # Moss and lichen

datasets:
  X:
    canopy_height: ETH_GlobalCanopyHeight_2020_v1_1km
    modis: modis_sur_refl_monthly_avg_1km
    soilgrids: soilgrids_v2-0_1km
    vodca: vodca_mean-p5-p95_1km
    worldclim: wc2-1_30s_bio
  Y:
    splot: splot4-0
    gbif: all_tracheophyta_non-cult_2024-04-10
    use: "splot_gbif" # Which trait dataset(s) to use for training, separated by "_"
    trait_stat: 1 # ('mean', 'std', 'median', 'q05', 'q95', 'count') (bands start at 1)
    traits:
      - 4 # Stem specific density (SSD) or wood density (stem dry mass per stem fresh volume)
      - 6 # Root rooting depth
      - 11 # Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): undefined if petiole is included or excluded)
      - 13 # Leaf carbon (C) content per leaf dry mass
      - 14 # Leaf nitrogen (N) content per leaf dry mass
      - 15 # Leaf phosphorus (P) content per leaf dry mass
      - 18 # Plant height
      - 21 # Stem diameter
      - 26 # Seed dry mass
      - 27 # Seed length
      - 46 # Leaf thickness
      - 47 # Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)
      - 50 # Leaf nitrogen (N) content per leaf area
      - 55 # Leaf dry mass (single leaf)
      - 78 # Leaf nitrogen (N) isotope signature (delta 15N)
      - 95 # Seed germination rate (germination efficiency)
      - 138 # Seed number per reproduction unit
      - 144 # Leaf length
      - 145 # Leaf width
      - 146 # Leaf carbon/nitrogen (C/N) ratio
      - 163 # Leaf fresh mass
      - 169 # Stem conduit density (vessels and tracheids)
      - 223 # Species genotype: chromosome number
      - 224 # Species genotype: chromosome cDNA content
      - 237 # Dispersal unit length
      - 281 # Stem conduit diameter (vessels, tracheids)
      - 282 # Wood vessel element length; stem conduit (vessel and tracheids) element length
      - 289 # Wood fiber lengths
      - 1080 # Root length per root dry mass (specific root length, SRL)
      - 3112 # Leaf area (in case of compound leaves: leaf, undefined if petiole in- or excluded)
      - 3113 # Leaf area (in case of compound leaves: leaflet, undefined if petiole is in- or excluded)
      - 3114 # Leaf area (in case of compound leaves: undefined if leaf or leaflet, undefined if petiole is in- or excluded)
      - 3120 # Leaf water content per leaf dry mass (not saturated)

eo_data:
  interim:
    dir: eo_data
  predict:
    dir: predict
    filename: eo_predict.parquet

worldclim:
  bio_vars:
    - "1" # Annual Mean Temperature
    - "4" # Temperature Seasonality (standard deviation ×100)
    - "7" # Temperature Annual Range (BIO5-BIO6)
    - "12" # Annual Precipitation
    - "13-14" # Annual precipitation range (BIO13-BIO14)
    - "15" # Precipitation Seasonality (Coefficient of Variation)

gbif:
  raw:
    dir: all_tracheophyta_non-cult_2024-04-10
  interim:
    dir: gbif
    matched: gbif_pfts.parquet
    subsampled: gbif_subsampled.parquet
    subsample_binsize: 4
    subsample_n_max: 10000
    traits: trait_maps

splot:
  raw:
    dir: splot4-0
  interim:
    dir: splot
    extracted: extracted
    traits: trait_maps

trydb:
  raw:
    dir: TRY_5_GapFilledData_2020
    zip: TRY_5_GapFilledData_2020.zip
    zipfile_csv: TRY_50_2020_01/gapfilled_data/mean_gap_filled_back_transformed_incl_species_names.csv
    pfts: try_pft_v1.csv
  interim:
    dir: try
    extracted_csv: mean_gf_bt_sp.csv
    quantile_range: [0.005, 0.995]
    filtered: mean_gf_bt_sp_filt.parquet

train:
  dir: data/features
  features: features.parquet
  spatial_autocorr: spatial_autocorr.parquet
  cv_splits:
    range_stat: "median"
    n_splits: 10
    n_sims: 100
    dir: skcv_splits
  arch: "autogluon"
  eval_results: evaluation_results.csv
  feature_importance: feature_importance.csv

processed:
  dir: data/processed
  predict_dir: predict
  aoa_dir: aoa
  cov_dir: cov
  splot_corr: splot_correlation.csv

autogluon:
  included_model_types: ["FASTAI", "GBM", "NN_TORCH", "XT", "XGB"]
  presets: "high"
  save_bag_folds: true
  refit_full: false
  set_best_to_refit_full: false
  time_limit: 12600 # 3.5 hours per trait
  num_gpus: 4
  feature_importance: true
  FI_time_limit: 3600
  leaderboard: leaderboard.csv

models:
  dir: models
