model_res: "001"
PFT: "Shrub_Tree_Grass"
mask:
  path: data/raw/esa_worldcover_v100_1km/esa_worldcover_v100_1km.tif
  keep_classes:
    - 10 # Tree cover
    - 20 # Shrubland
    - 30 # Grassland
    - 40 # Cropland
    - 60 # Bare/sparse vegetation
    - 70 # Snow and ice
    - 90 # Herbaceous wetland
    - 95 # Mangroves
    - 100 # Moss and lichen

datasets:
  X:
    # - ETH_GlobalCanopyHeight_2020_v1_1km
    - modis_sur_refl_monthly_avg_1km
    # - soilgrids_v2-0_1km
    # - vodca_mean-p5-p95_1km
    - wc2-1_30s_bio
  Y:
    splot: splot4-0
    gbif: all_tracheophyta_non-cult_2024-04-10

gbif:
  raw:
    dir: data/raw/all_tracheophyta_non-cult_2024-04-10

trydb:
  raw:
    pfts: data/raw/try_pft_v1.csv

base_resolution: 0.01 # Shared best resolution of all datasets (used for masking)
target_resolution: 0.01 # Target resolution for model training
extent: [-180, -60, 180, 90] # Extent of the final dataset

interim:
  eo_data: data/interim/eo_data
  splot:
    dir: data/interim/splot
  gbif:
    dir: data/interim/gbif

train:
  path: data/processed/train
