version: "0.1.0"
model_res: "02"
PFT: "Shrub_Tree_Grass"
random_seed: 42
base_resolution: 0.01 # Shared best resolution of all EO datasets (used for masking)
target_resolution: 0.2 # Target resolution for model training
extent: [-180, -60, 180, 90] # Extent of the final dataset
raw_dir: data/raw
interim_dir: data/interim
processed_dir: data/processed
dask_dashboard: ":39143"
trait_mapping: "reference/trait_mapping.json"
trait_stat_mapping: "reference/trait_stat_mapping.json"

pylos:
  "001":
    build_splot_maps:
      npartitions: 60
      dask:
        n_workers: 40
        memory_limit: 40GB
    featurize_train:
      n_chunks: 6
      n_workers: 30
      memory_limit: null
    build_predict:
      n_chunks: 5
      n_workers: null
      memory_limit: 100GB
      impute_chunks: 3
    calc_spatial_autocorr:
      n_workers: 60
      n_workers_variogram: 5
    skcv_splits:
      n_workers: 60
  "02":
    build_splot_maps:
      npartitions: 60
      dask:
        n_workers: 60
        memory_limit: 40GB
    featurize_train:
      n_chunks: 1
      n_workers: 60
      memory_limit: null
    build_predict:
      n_chunks: 1
      n_workers: null
      memory_limit: 100GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 60
      n_workers_variogram: 5
    skcv_splits:
      n_workers: 60
  "05":
    featurize_train:
      n_chunks: 1
      n_workers: 30
      memory_limit: null
    build_predict:
      n_chunks: 1
      n_workers: null
      memory_limit: 100GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 60
      n_workers_variogram: 5
    skcv_splits:
      n_workers: 60
  "1":
    featurize_train:
      n_chunks: 1
      n_workers: 30
      memory_limit: null
    build_predict:
      n_chunks: 1
      n_workers: null
      memory_limit: 100GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 60
      n_workers_variogram: 5
    skcv_splits:
      n_workers: 60
  "2":
    featurize_train:
      n_chunks: 1
      n_workers: 30
      memory_limit: null
    build_predict:
      n_chunks: 1
      n_workers: null
      memory_limit: 100GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 60
      n_workers_variogram: 5
    skcv_splits:
      n_workers: 60
geos:
  "001":
    featurize_train:
      n_chunks: 2
      n_workers: 100
      memory_limit: 150GB
    build_predict:
      n_chunks: 3
      n_workers: 100
      memory_limit: 500GB
      impute_chunks: 2
    calc_spatial_autocorr:
      n_workers: 100
      n_workers_variogram: 20
    skcv_splits:
      n_workers: 80
  "02":
    featurize_train:
      n_chunks: 1
      n_workers: 100
      memory_limit: 150GB
    build_predict:
      n_chunks: 1
      n_workers: 100
      memory_limit: 500GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 100
      n_workers_variogram: 20
    skcv_splits:
      n_workers: 80
  "05":
    featurize_train:
      n_chunks: 1
      n_workers: 100
      memory_limit: 150GB
    build_predict:
      n_chunks: 1
      n_workers: 100
      memory_limit: 500GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 100
      n_workers_variogram: 20
    skcv_splits:
      n_workers: 80
  "1":
    featurize_train:
      n_chunks: 1
      n_workers: 100
      memory_limit: 150GB
    build_predict:
      n_chunks: 1
      n_workers: 100
      memory_limit: 500GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 100
      n_workers_variogram: 20
    skcv_splits:
      n_workers: 80
  "2":
    featurize_train:
      n_chunks: 1
      n_workers: 100
      memory_limit: 150GB
    build_predict:
      n_chunks: 1
      n_workers: 100
      memory_limit: 500GB
      impute_chunks: 1
    calc_spatial_autocorr:
      n_workers: 100
      n_workers_variogram: 20
    skcv_splits:
      n_workers: 80

mask:
  path: data/raw/esa_worldcover_v100_1km/esa_worldcover_v100_1km.tif
  keep_classes:
    - 10 # Tree cover
    - 20 # Shrubland
    - 30 # Grassland
    - 40 # Cropland
    - 60 # Bare/sparse vegetation
    - 70 # Snow and ice
    - 90 # Herbaceous wetland
    - 95 # Mangroves
    - 100 # Moss and lichen

datasets:
  X:
    canopy_height: ETH_GlobalCanopyHeight_2020_v1_1km
    modis: modis_sur_refl_monthly_avg_1km
    soilgrids: soilgrids_v2-0_1km
    vodca: vodca_mean-p5-p95_1km
    worldclim: wc2-1_30s_bio
  Y:
    splot: splot4-0
    gbif: all_tracheophyta_non-cult_2024-04-10
    trait_stats: ["mean", "std", "median", "q05", "q95", "count"]
    trait_stat: 1 # ('mean', 'std', 'median', 'q05', 'q95', 'count') (bands start at 1)
    traits:
      - 4 # Stem specific density (SSD) or wood density (stem dry mass per stem fresh volume)
      - 6 # Root rooting depth
      - 11 # Leaf area per leaf dry mass (specific leaf area, SLA or 1/LMA): undefined if petiole is included or excluded)
      - 13 # Leaf carbon (C) content per leaf dry mass
      - 14 # Leaf nitrogen (N) content per leaf dry mass
      - 15 # Leaf phosphorus (P) content per leaf dry mass
      - 18 # Plant height
      - 21 # Stem diameter
      - 26 # Seed dry mass
      - 27 # Seed length
      - 46 # Leaf thickness
      - 47 # Leaf dry mass per leaf fresh mass (leaf dry matter content, LDMC)
      - 50 # Leaf nitrogen (N) content per leaf area
      - 55 # Leaf dry mass (single leaf)
      - 78 # Leaf nitrogen (N) isotope signature (delta 15N)
      - 95 # Seed germination rate (germination efficiency)
      - 138 # Seed number per reproduction unit
      - 144 # Leaf length
      - 145 # Leaf width
      - 146 # Leaf carbon/nitrogen (C/N) ratio
      - 163 # Leaf fresh mass
      - 169 # Stem conduit density (vessels and tracheids)
      - 223 # Species genotype: chromosome number
      - 224 # Species genotype: chromosome cDNA content
      - 237 # Dispersal unit length
      - 281 # Stem conduit diameter (vessels, tracheids)
      - 282 # Wood vessel element length; stem conduit (vessel and tracheids) element length
      - 289 # Wood fiber lengths
      - 1080 # Root length per root dry mass (specific root length, SRL)
      - 3112 # Leaf area (in case of compound leaves: leaf, undefined if petiole in- or excluded)
      - 3113 # Leaf area (in case of compound leaves: leaflet, undefined if petiole is in- or excluded)
      - 3114 # Leaf area (in case of compound leaves: undefined if leaf or leaflet, undefined if petiole is in- or excluded)
      - 3120 # Leaf water content per leaf dry mass (not saturated)

eo_data:
  interim:
    dir: eo_data
  predict:
    dir: predict
    mask_fn: eo_predict_mask.parquet
    imputed_fn: eo_predict_imputed.parquet

worldclim:
  bio_vars:
    - "1" # Annual Mean Temperature
    - "4" # Temperature Seasonality (standard deviation ×100)
    - "7" # Temperature Annual Range (BIO5-BIO6)
    - "12" # Annual Precipitation
    - "13-14" # Annual precipitation range (BIO13-BIO14)
    - "15" # Precipitation Seasonality (Coefficient of Variation)

gbif:
  raw:
    dir: all_tracheophyta_non-cult_2024-04-10
  interim:
    dir: gbif
    matched: gbif_pfts.parquet
    subsampled: gbif_subsampled.parquet
    subsample_binsize: 4
    subsample_n_max: 10000
    traits: trait_maps

splot:
  raw:
    dir: splot4-0
  interim:
    dir: splot
    extracted: extracted
    traits: trait_maps

trydb:
  raw:
    dir: TRY_5_GapFilledData_2020
    zip: TRY_5_GapFilledData_2020.zip
    zipfile_csv: TRY_50_2020_01/gapfilled_data/mean_gap_filled_back_transformed_incl_species_names.csv
    pfts: try_pft_v1.csv
  interim:
    dir: try
    extracted_csv: mean_gf_bt_sp.csv
    quantile_range: [0.005, 0.995]
    filtered: mean_gf_bt_sp_filt.parquet

train:
  dir: data/features
  Y:
    fn: Y.parquet
  missing_val_thresh: 0.4 # Drop features with more than this fraction of missing values
  spatial_autocorr: spatial_autocorr.parquet
  cv_splits:
    range_stat: "median"
    n_splits: 5
    n_sims: 100
    dir: skcv_splits
  weights:
    fn: feature_weights.parquet
    method: manual # "auto", "manual" -- "manual" will use below weights
    splot: 1.0
    gbif: 0.08661
  arch: "autogluon"
  eval_results: evaluation_results.csv
  feature_importance: feature_importance.csv

processed:
  dir: data/processed
  predict_dir: predict
  aoa_dir: aoa
  cov_dir: cov
  splot_corr: splot_correlation.csv

autogluon:
  included_model_types: ["GBM"]
  presets: "high"
  save_bag_folds: true
  refit_full: false
  set_best_to_refit_full: false
  cv_fit_time_limit: 3600
  full_fit_time_limit: 12600 # 3.5 hours per trait
  num_gpus: "auto"
  num_cpus: 64
  feature_importance: true
  FI_time_limit: 1800
  FI_num_shuffle_sets: 10

models:
  dir: models

aoa:
  dir: aoa
  device_ids: [0, 1, 2, 3]
  predict_sample: 0.5
  splot:
    train_sample: 1
    avg_dist_batch_size: 10000
    predict_partitions: null
  splot_gbif:
    train_sample: 0.5
    avg_dist_batch_size: 5000
    predict_partitions: null
  
predict:
  dir: predict
  geos:
    n_workers: 14
    batches: 24
  pylos:
    n_workers: 4
    batches: 24

cov:
  dir: cov
  
public:
  dir: PANOPS/cit-sci-traits/trait_maps
